management:
  endpoint:
    health:
      enabled: true

spring:
  jpa.hibernate:
    ddl-auto: validate
  jpa.properties.hibernate:
    show-sql: true
    format_sql: true
    jdbc.lob.non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 50
      leak-detection-threshold: 60000
      idle-timeout: 60000
      minimum-idle: 3
      driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog.yml